services:
  - type: web
    name: narasimhastills
    env: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
